name: Publish Docker image with source code versioning to GitHub Container Registry

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Extract version from source code
        id: get_version
        run: |
          VERSION=$(python -c "from logic.version import __version__; print(__version__)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from source code
        run: |
          VERSION=$(python -c "from logic.version import __version__; print(__version__)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image with source code version tag
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-app:$VERSION .
          docker push ghcr.io/${{ github.repository }}/my-app:$VERSION
        env:
          VERSION: ${{ env.VERSION }}