name: Publish Docker image with source code versioning to GitHub Container Registry

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from source code
        run: |
          VERSION=$(awk 'NR==1 {print $3}' main.py | tr -d "'")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image with source code version tag
        run: |
          docker build -t ghcr.io/${{ github.repository }}/app:$VERSION -t ghcr.io/${{ github.repository }}/app:latest .
          docker push ghcr.io/${{ github.repository }}/app:$VERSION
          docker push ghcr.io/${{ github.repository }}/app:latest
        env:
          VERSION: ${{ env.VERSION }}