name: Publish Docker image with source code versioning to GitHub Container Registry

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest test

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from source code
        run: |
          VERSION=$(awk 'NR==1 {print $3}' main.py | tr -d "'")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"
  
      - name: Build and push Docker image with source code version tag
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:latest
          build-args: |
            VERSION=${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64
